SELECT OBJECT_NAME AS name, OBJECT_TYPE AS type, OWNER AS parentname FROM SYS.ALL_OBJECTS;
SELECT COLUMN_NAME AS name, 'COLUMN' AS type, TABLE_NAME AS parentname FROM SYS.ALL_TAB_COLUMNS;
SELECT TRIGGER_NAME AS name, 'TRIGGER' AS type, TABLE_NAME AS parentname FROM SYS.ALL_TRIGGERS;
SELECT USERNAME AS name, 'USER' AS type, NULL AS parentname FROM SYS.ALL_USERS;